### PR TITLE
Feature: Enable the developer to point to a specific subscription, to…

### PR DESCRIPTION
**Pull request by Splaxi**
… ensure the correct billing.

When this gets added, we should update the readme file or create a wiki page, to instruct people how to edit the files, when they want to run local unit tests of the module.

I'll be happy to assist with any of it.

### CODE REVIEW

**Comment by tmeadon** [comment]
If you have time to, that would be great! Cheers!

**Comment by Splaxi** [comment]
And I believe we have what we are looking for!

**Comment by tmeadon** [comment]
Do you think in the case of the parameters for the build script it would be good to make it clear what part of the build those options relate to?  Maybe by renaming to something like 'SubscriptionIdForTests'?

**Comment by Splaxi** [comment]
I can see your point.

If we change the parameter names for the `PSServiceBus.build.ps1` file, then it would make sense when trying to run the `Invoke-Build` command from the root folder.

But for the other functions, the names should be as they are now.

Let me know if we agree, then I'll make the change and push it to you...

**Comment by Splaxi** [comment]
I suggest:

-UnitTestSubscriptionId
-UnitTestLocation

As the names for the parameters in the `PSServiceBus.build.ps1`

**Comment by tmeadon** [comment]
I've always considered these tests as integration tests, hence the directory structure.  I think we should avoid using 'unit' if we can to prevent confusion.  Since we only have one type of tests maybe these would be alright:

-TestSubscriptionId
-TestLocation

**Comment by Splaxi** [comment]
It is done and pushed!

**Comment by tmeadon** [comment]
Excellent - merged!

**Pull request merged**
