### PR TITLE
Refactor NumberOfMessagesToRetrieve to ReceiveQty 

### PR DESCRIPTION
**Pull request by Splaxi**
When looking at the naming convention for the Get-SbMessage, the following is true:

The end user want to read message(s) from a Service Bus Queue or a Service Bus Topic / Subscription. 

It shouldn't be necessary for us to be that explicit with the NumberOfMessagesToRetrieve parameter versus ReceiveQty.

### CODE REVIEW

**Comment by Splaxi** [comment]
Ready for review by @tommagumma

**Comment by tmeadon** [comment]
Should we leave `NumberOfMessagesToRetrieve` in as an alias for now so that this isn't a breaking change?

**Comment by Splaxi** [comment]
Great idea! We totally should do that!

**Comment by Splaxi** [comment]
@tommagumma Done!

**Review by tmeadon — APPROVED** [review]
Looking good @Splaxi, thanks!

**Pull request merged**
