### PR TITLE
Implement receivebatchqty and prefetchqty for purge

### PR DESCRIPTION
**Pull request by Splaxi**

### CODE REVIEW

**Comment by Splaxi** [comment]
@tommagumma This should be ready for review 🤞

**Comment by tmeadon** [comment]
This is looking good to me!  Please could you just expand on the descriptions for the new parameters to make their use case a bit clearer?  Why might I want to use the -PrefetchQty parameter?  That kind of thing.

Cheers!

**Comment by Splaxi** [comment]
Let me know if this is what you're looking for.

**Comment by Splaxi** [comment]
I might have hit a bug. 

Give me some time to do some more testing!

**Comment by Splaxi** [comment]
I found the issue, will refactor a tiny bit and get to you. Expect it to be done monday.

**Comment by tmeadon** [comment]
Sounds good!

**Comment by Splaxi** [comment]
Ready for next round of review dear @tommagumma

**Pull request merged**
